[phases.setup]
nixPkgs = ["python312", "chromium"]

[phases.install]
cmds = [
    "pip install -r job_scraper/requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "cd job_scraper && python web_app.py"
