[phases.setup]
nixPkgs = [
    "python312",
    "chromium",
    "nss",
    "freetype",
    "harfbuzz",
    "ca-certificates",
    "fontconfig",
    "libdrm",
    "mesa",
    "libxkbcommon",
    "pango",
    "atk",
    "gtk3",
    "glib",
    "alsa-lib",
    "cups"
]

[phases.install]
cmds = [
    "pip install -r job_scraper/requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "bash start.sh"
